version: '3.8'

services:
  agencia-up-front:
    build: .
    container_name: agencia-up-front
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
    volumes:
      - ./logs:/app/logs
    networks:
      - app-network

  # Nginx como proxy reverso (opcional)
  nginx:
    image: nginx:alpine
    container_name: agencia-up-front-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./ssl:/etc/nginx/ssl
    depends_on:
      - agencia-up-front
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  logs:
